package entidades;
// Generated 14/07/2019 08:13:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int idPersonal;
     private String nombre;
     private String dni;
     private String telef;
     private String corgo;
     private String email;
     private String apellido;
     private Set atencions = new HashSet(0);
     private Set cargopersonals = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int idPersonal, String nombre, String dni, String telef, String corgo, String email, String apellido) {
        this.idPersonal = idPersonal;
        this.nombre = nombre;
        this.dni = dni;
        this.telef = telef;
        this.corgo = corgo;
        this.email = email;
        this.apellido = apellido;
    }
    public Personal(int idPersonal, String nombre, String dni, String telef, String corgo, String email, String apellido, Set atencions, Set cargopersonals) {
       this.idPersonal = idPersonal;
       this.nombre = nombre;
       this.dni = dni;
       this.telef = telef;
       this.corgo = corgo;
       this.email = email;
       this.apellido = apellido;
       this.atencions = atencions;
       this.cargopersonals = cargopersonals;
    }
   
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTelef() {
        return this.telef;
    }
    
    public void setTelef(String telef) {
        this.telef = telef;
    }
    public String getCorgo() {
        return this.corgo;
    }
    
    public void setCorgo(String corgo) {
        this.corgo = corgo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set atencions) {
        this.atencions = atencions;
    }
    public Set getCargopersonals() {
        return this.cargopersonals;
    }
    
    public void setCargopersonals(Set cargopersonals) {
        this.cargopersonals = cargopersonals;
    }




}


